### ISSUE TITLE
Slow operations in `HeroUpdateHook`

### ISSUE THREAD

**Issue by SFGrenade** [HKLab/DCParry#1]
https://github.com/HKLab/DCParry/blob/06c88fa65a973507f7eb2a4dcb8b242b72f9046a/Scripts/DCParryMod.cs#L14-L17

This is slow and will reduce FPS by roughly 10%.
Maybe try `On.HeroController.Start` instead of `Modding.ModHooks.HeroUpdateHook`

**Comment by HKLab** [comment]
Thanks
